kind: Namespace
apiVersion: v1
metadata:
  name: cicd

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-manager
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: cicd
roleRef:
  kind: ClusterRole
  name: namespace-manager
  apiGroup: rbac.authorization.k8s.io

---
kind: Secret
apiVersion: v1
metadata:
  name: cleaner-vsts
  namespace: cicd
type: Opaque
data:
  vsts_pat: <your pat>

---
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  namespace: cicd
  name: namespace-cleaner
spec:
  # run daily at 1 am
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleaner
            image: tobyto/kube-namespace-cleaner
            env:
            - name: MAX_NAMESPACE_INACTIVE_HOURS
              value: "24"
            - name: NS_WHITELIST
              value: "aether-master,aether-demo"
            - name: VSTS_PAT
              valueFrom:
                secretKeyRef:
                  name: cleaner-vsts
                  key: vsts_pat
          # pod sometimes losts connection to network, restart will keep failing
          activeDeadlineSeconds: 30
          restartPolicy: Never
          