kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: {{ template "namespace-cleaner.name" . }}
    chart: {{ template "namespace-cleaner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "namespace-cleaner.fullname" . }}